server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item_mania_db?serverTimezone=UTC&useSSL=false
    username: root
    password: qAqR1532!#
    driver-class-name: com.mysql.cj.jdbc.Driver